name: Bug Report
description: Report a reproducible defect
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: Provide exact steps and commands.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, versions, Docker/Python/Node info.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste logs or attach screenshots.
